# Generated by Django 6.0.4 on 2026-04-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ (slug)')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена (MDL)')),
                ('genre', models.CharField(choices=[('fantasy', 'Фэнтези'), ('scifi', 'Sci-Fi'), ('cute', 'Милые'), ('dark', 'Мрачные')], max_length=50, verbose_name='Жанр')),
                ('featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('material', models.CharField(max_length=200, verbose_name='Материал')),
                ('size', models.CharField(max_length=100, verbose_name='Размер')),
                ('print_time', models.CharField(max_length=100, verbose_name='Время печати')),
                ('colors', models.CharField(max_length=200, verbose_name='Цвета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('emoji', models.CharField(default='🐉', max_length=10, verbose_name='Эмодзи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('customer_address', models.TextField(verbose_name='Адрес доставки')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('fill', models.CharField(max_length=100, verbose_name='Заполнение')),
                ('notes', models.TextField(blank=True, verbose_name='Пожелания')),
                ('total_price', models.IntegerField(verbose_name='Итого (MDL)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('printing', 'Печатается'), ('done', 'Готов'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
