# Generated by Django 4.2.30 on 2026-04-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customorder_multicolor_total_price_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='select_variant',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='caption',
        ),
    ]
